#╔═════════════════════════════════════════════════════════════════════════════╗
#║ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░║
#║ Main config file for snakemake run                                          ║
#║ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░║
#╚═════════════════════════════════════════════════════════════════════════════╝

# TODO add location of config extra relative to the base folder
experiment_name: "Test stringie"
rungroup: ""
threads: 15

metadata: "metadata.tsv"
# if empty, default 'config_extra.yaml' will be loaded
extra_config: 
paired_read_strings: ["_1", "_2"]

species: "mouse"
index: /home/ingwarr/genomes/ncbi_grcm38/star/
gtf: "/home/ingwarr/genomes/ncbi_grcm38/annotation/gencode.vM25.annotation.gtf"
fasta: "/home/ingwarr/genomes/ncbi_grcm38/fasta/GRCm38.primary_assembly.genome.fa"

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Pipeline config =====                                                 │
#└─────────────────────────────────────────────────────────────────────────────┘
# pipelines are defined in snakemake/rules/pipelines.smk
# see README for list of available pipelines
pipeline: "deseq"

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Preprocess config =====                                               │
#└─────────────────────────────────────────────────────────────────────────────┘
# extra options are found in config_extra.yaml or can be specified directly and
# will be run 'as is'
preprocess:
  # can be specified as percentage (number smaller than 1) or absolute number of
  # reads to be kept (whole number 1 or greater). If empty, no subsetting will
  # be performed.
  subsample:
  extra: ""

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Trimming config =====                                                 │
#└─────────────────────────────────────────────────────────────────────────────┘
# extra options are found in config_extra.yaml or can be specified directly and
# will be run 'as is'
trim:
  # one of 'fastp', 'cutadapt' or 'trimmomatic'. If nothing is specified, 
  # trimming will be skipped
  trimmer: ""
  quality: ""
  extra: ""

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Align config =====                                                    │
#└─────────────────────────────────────────────────────────────────────────────┘
# extra options are found in config_extra.yaml or can be specified directly and
# will be run 'as is'
align:
  extra: ""

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Coverage config =====                                                 │
#└─────────────────────────────────────────────────────────────────────────────┘
# should bedgraph and tdf files be generated for bam files
# possible choices for normalization: RPKM, CPM, BPM, RPGC, None
# RPGC normalization requires the --effectiveGenomeSize to be specified in extra
# https://deeptools.readthedocs.io/en/develop/content/tools/bamCoverage.html
# extra options are found in config_extra.yaml or can be specified directly and
# will be run 'as is'
coverage:
  calculate: FALSE
  split_strands: FALSE
  bin_size: "10"
  normalize_using: "BPM"
  extra: ""

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Read counting config =====                                            │
#└─────────────────────────────────────────────────────────────────────────────┘
# strandedness is specified in the metadata.tsv file
# extra options are found in config_extra.yaml or can be specified directly and
# will be run 'as is'
count:
  # if multimapping reads should be counted
  multimap: FALSE
  # if reads belonging to the overlapping genes should be counted
  overlap: TRUE
  # Several tools, namely Cufflinks and Stringtie offer refererence guided and
  # denovo assembly of transcripts.
  # One of: "none", "guided", "denovo". If empty, no assembly will be used.
  # If unsupported, this option is ignored.
  transcript_assembly: "none"
  extra: ""

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Differential expression config =====                                  │
#└─────────────────────────────────────────────────────────────────────────────┘
diffexp:
  # name of the analysis and final output directory
  outdir: "default"
  # ordering of the reference levels from which contrasts will be costructed
  # name is a column in the metadata file
  # if only one level is specified it is taken as baseline
  # if empty, alphabetical order will be used
  reference_levels:
    group: ["alg", "lmcd"]
  # the default value for one design variable is 'group'
  # if only one grouping variable is present, specify it as is
  # if you wish to use formula to combine multiple groups, mark the beginning
  # with ~ any combination of columns present in metadata file is possible
  # for sleuth this corresponds to the full model
  # TODO maybe rename to model_design
  # TODO for sleuth if multiple groups are present, the design matrix needs
  ## to be reconstructed with different terms to generate all combinations
  design: "group"
  # used in sleuth
  model_reduced: "~1"
  # see README for explanation of different contrast types
  # TODO for cufdiff only simple contrast is possible
  # TODO rename contrast types. suggestions
  # A - simple
  # B - named
  # C - numeric
  # D - sleuth_lrt - reduced model
  # E - design_matrix
  contrast_type: "A"
  # for contrast type 'simple', values are taken from 'design'
  # TODO maybe rename to results or something similar
  contrasts: "group"
  fdr: 0.05
  # filter out genes that have smaller total amount of reads across all samples
  gene_min_readcount: 10
  input_gene_ids: "ENSEMBL"
  output_gene_ids: "SYMBOL"
  # drop genes from output that don't map to any gene symbol
  # otherwise they will be replaced by gene id
  drop_no_symbol: TRUE
  extra: ""


#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Reporting config =====                                                │
#└─────────────────────────────────────────────────────────────────────────────┘
# TODO change annotation to list to support multi level annotation
report:
  # one of:
  # 'default' - regular web page
  # 'flex' - dashboard-like output
  layout: "flex"
  # export all samples in one html report or divide reports per-sample
  # individual reduces the loading time of report with many comparisons
  individual: FALSE
  # saves css and js files for html report in separate folder, reduces overall 
  # size
  self_contained: FALSE
  pca:
    groups: ["group"]
    ngenes: 1000
    top_pcas: 6
    top_gene_loadings: 25
    pca2go_ngenes: 10000
    pca2go_loadings_ngenes: 500
  sample_heatmap:
    # can be one of the following: mean, variance, diff
    mode: "variance"
    ngenes: 1000
    # one of the following: euclidean, correlation or none for no clustering
    cluster_metric_col: "euclidean"
    cluster_metric_row: "euclidean"
    annotation: "group"
  sample_distances_heatmap:
    annotation: "group"
  upset:
    max_groups: 40
    min_group_size: 3
  mdplot_group: "group"

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Export files config =====                                             │
#└─────────────────────────────────────────────────────────────────────────────┘
gsea:
  ranking: "sign_fc_pval"

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Additional miscellaneous options =====                                │
#└─────────────────────────────────────────────────────────────────────────────┘
# create tar.gz archive with results for differentially expressed genes, counts
# and logs
result_archive: FALSE
