#╔═════════════════════════════════════════════════════════════════════════════╗
#║ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░║
#║ Additional configuration options for Snakemake run                          ║
#║ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░║
#╚═════════════════════════════════════════════════════════════════════════════╝

# To be able to reuse and store extra configs, create a unique extra config
# name under appropriate step (align, count, etc.) and then pass this name into 
# the extra parameter in the config.yaml file.

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Trim config =====                                                     │
#└─────────────────────────────────────────────────────────────────────────────┘
trim:
  fastp_default: ""
  cutadapt_default: ""
  trimmomatic_default: ""
  # see https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types
  adapters_single: ""
  adapters_paired: ""
  # see https://cutadapt.readthedocs.io/en/stable/guide.html#quality-trimming

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Align config =====                                                    │
#└─────────────────────────────────────────────────────────────────────────────┘
align:
  # optimized extra parameters for tophat
  tophat_extra:
    "-N 18
    --read-edit-dist 18"
  # optimized extra parameters for star
  star_extra:
    "--outFilterMismatchNmax 33
    --alignEndsType Local
    --alignSJoverhangMin 8
    --outFilterScoreMinOverLread 0
    --outFilterMatchNminOverLread 0
    --outFilterMatchNmin 0
    --seedSearchStartLmax 12"
  # optimized extra parameters for hisat
  hisat_extra:
    "--mp 1,0
    --sp 3,1
    --pen-noncansplice 15"
  kallisto_extra:
    ""
  # required for single end run, estimated for paired end
  kallisto_single_fragment_info:
    "-l 200 -s 10"
  salmon_extra:
    "--numBootstraps 100"
  salmon_single_fragment_info:
    "--fldMean 400 --fldSD 10"

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Read counting config =====                                            │
#└─────────────────────────────────────────────────────────────────────────────┘
count:
  featurecounts_extra: ""
  htseq_extra: ""
  stringtie_extra: ""


count_other_rules:
  stringtie_assemble_extra: ""
  stringtie_merge_extra: ""
  cufflinks_extra: ""
  cuffquant_extra: ""
  cuffmerge_extra: ""
  cuffnorm_extra: ""

tximport_count_matrix:
  # leave empty or use auto to determine automatically from which tool output
  # will the count matrix be created
  tool: ""
  # supply either as dictionary or yaml entries that will be parsed to named
  # vector in R script
  extra: ""

#┌─────────────────────────────────────────────────────────────────────────────┐
#│ ===== Differential expression config =====                                  │
#└─────────────────────────────────────────────────────────────────────────────┘
diffexp:
  # deseq2 lfc shrink algorithm type
  # apeglm is not yet implemented
  deseq_lfc_shrink: "ashr"
  # classic or glm contrasts approach
  edger_analysis_type: "classic"
