experiment_name: "Liver_cancer_project"
threads: 15
pandoc_path: "/usr/lib/rstudio-server/bin/quarto/bin/tools"

metadata: "metadata.tsv"
paired_read_strings: ["_1", "_2"]

species: "mouse"
index: "/shared/genome/grcm38/star"
gtf: "/shared/genome/grcm38/annotation/grcm38.gtf"
fasta: "/shared/genome/grcm38/fasta/grcm38.fa"

# pipeline ---------------------------------------------------------------------
# pipelines are defined in snakemake/rules/pipelines.smk
# see README for list of available pipelines
pipeline: "download_only"

# trimming ---------------------------------------------------------------------
# should reads be trimmed for adapters and/or quality, uses cutadapt
# if no trimming parameters are specified, trimming will be skipped
trim:
  # see https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types
  adapters_single: ""
  adapters_paired: ""
  # see https://cutadapt.readthedocs.io/en/stable/guide.html#quality-trimming
  quality: ""
  extra: ""

# align options ----------------------------------------------------------------
align:
  extra: "star_extra_1"

# coverage ---------------------------------------------------------------------
# should bedgraph and tdf files be generated for bam files
# possible choices for normalization: RPKM, CPM, BPM, RPGC, None
# RPGC normalization requires the --effectiveGenomeSize to be specified in extra
# https://deeptools.readthedocs.io/en/develop/content/tools/bamCoverage.html
coverage:
  calculate: "no"
  split_strands: "no"
  bin_size: "10"
  normalize_using: "BPM"
  extra: ""

# counting options -------------------------------------------------------------
# strandedness is specified in the metadata.tsv file
# for extra parameters to be passed to counting programs, see config_extra.yaml
count:
  # if multimapping reads should be counted
  multimap: "no"
  # if reads belonging to the overlapping genes should be counted
  # for extra parameters to specify the counting scores use config_extra.yaml
  overlap: "yes"

# differential expression options ----------------------------------------------
diffexp:
  # name of the analysis and final output directory
  outdir: "default"
  # the default value for one design variable is 'group'
  # if only one grouping variable is present, specify it as is
  # if you wish to use formula to combine multiple groups, mark the beginning
  # with ~ any combination of columns present in metadata file is possible
  design: "group"
  # ordering of the reference levels from which contrasts will be costructed
  # name is a column in the metadata file
  # if only one level is specified it is taken as baseline
  # if empty, alphabetical order will be used
  reference_levels:
    group: ["alg, lmcd, liver"]
  # see README for explanation of different contrast types
  contrast_type: "A"
  contrasts: "group"
  fdr: 0.05
  # filter out genes that have smaller total amount of reads across all samples
  gene_min_readcount: 10
  input_gene_ids: "ENSEMBL"
  output_gene_ids: "SYMBOL"
  # drop genes from output that don't map to any gene symbol
  # otherwise they will be replaced by gene id
  drop_no_sybmol: TRUE

# report options ---------------------------------------------------------------
report:
  # one of:
  # 'default' - regular web page
  # 'flex' - dashboard-like output
  layout: "flex"
  # export all samples in one html report or divide reports per-sample
  # individual reduces the loading time of report with many comparisons
  individual: FALSE
  # saves css and js files for html report in separate folder, reduces overall 
  # size
  self_contained: FALSE
  pca:
    groups: ["group"]
    ngenes: 1000
    top_pcas: 6
    top_gene_loadings: 25
    pca2go_ngenes: 10000
    pca2go_loadings_ngenes: 500
  sample_heatmap:
    # can be one of the following: mean, variance, diff
    mode: "variance"
    n_genes: 1000
    # one of the following: euclidean, correlation or none for no clustering
    cluster_metric_col: "euclidean"
    cluster_metric_row: "euclidean"
    annotation: "group"
  sample_distances_heatmap:
    annotation: "group"
  upset:
    max_groups: 40
    min_group_size: 3
  mdplot_group: "group"

gsea:
  ranking: "sign_fc_pval"
# additional miscellaneous options ---------------------------------------------
# create tar.gz archive with results for differentially expressed genes, counts
# and logs
result_archive: "no"
