---
title: 'PCA analysis'
author: "icervenka"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: paper
---

# Overview

Column {data-width=200}
-------------------------------------

### Proportion of explained variance

```{r scree_pev, echo = F, eval = T}
pcaExplorer::pcascree(pca_obj, title = "", type = "pev") %>% plotly::ggplotly()
```

### Cumulative proportion of explained variance

```{r scree_cev, echo = F, eval = T}
pcaExplorer::pcascree(pca_obj, title = "", type = "cev") # %>% plotly::ggplotly()
```


Column {data-width=600}
-------------------------------------

### PCA plots

```{r pca_plots, echo = F, eval = T}
plts <- purrr::map(combn(1:top_pcas, 2) %>% as.data.frame(), function(x) {
  pcaExplorer::pcaplot(
    r,
    intgroup = group,
    ntop = pca_ngenes,
    text_labels = FALSE,
    pcX = x[1],
    pcY = x[2]
  ) +
    ggplot2::theme(legend.position = "none")
})

plotly::subplot(plts, nrows = 4, titleX = TRUE, titleY = TRUE, margin = .04)
```

Column {data-width=200}
-------------------------------------

### Significance of PC correlation with covariates

```{r pc_heatmap, echo = F, eval = T}
heatmaply::heatmaply(
  -log10(pca_corr),
  Rowv = FALSE,
  Colv = FALSE,
  key.title = "-log10(pvalue)\nof correlation"
)
```

```{r child = 'render_pca_subpages.Rmd', eval = T}
```

`r paste(knitr::knit_child(text = out), collapse = '')`


