# Conda environments
CONDA_SHARED_ENV = ENV_DIR + 'shared.yaml'
CONDA_SRA_TOOLS_ENV = ENV_DIR + 'sra_tools.yaml'
CONDA_PREPROCESS_ENV = ENV_DIR + 'preprocess.yaml'
CONDA_CUTADAPT_ENV = ENV_DIR + 'cutadapt.yaml'
CONDA_QC_ENV = ENV_DIR + 'qc.yaml'
CONDA_ALIGN_GENERAL_ENV = ENV_DIR + 'align_general.yaml'
CONDA_ALIGN_OTHER_ENV = ENV_DIR + 'align_other.yaml'
CONDA_COUNT_GENERAL_ENV = ENV_DIR + 'count_general.yaml'
CONDA_COUNT_CUFFLINKS_ENV = ENV_DIR + 'count_cufflinks.yaml'
CONDA_R_GENERAL_ENV = ENV_DIR + 'r_general.yaml'
CONDA_DIFFEXP_GENERAL_ENV = ENV_DIR + 'diffexp_general.yaml'